name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.2.0'
          
      - name: Install required packages
        run: |
          R -e 'install.packages(c("shiny", "shinylive", "httpuv", "ncdf4", "ggplot2", "dplyr", "lubridate", "sf", "raster", "terra", "gridExtra", "scales", "viridis", "plotly"), repos="https://cloud.r-project.org")'
          
      - name: Build static app
        run: |
          R -e 'shinylive::export("app.R", "docs")'
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs 