name: Deploy to shinyapps.io

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.2.0'
      
      - name: Install dependencies
        run: |
          R -e "install.packages(c('shiny', 'rsconnect', 'ncdf4', 'ggplot2', 'dplyr', 'lubridate', 'sf', 'raster', 'terra', 'gridExtra', 'scales', 'viridis', 'plotly'))"
      
      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript deploy.R 